### ISSUE TITLE
How can i run this app?

### ISSUE THREAD

**Issue by miketwais** [isaced/NSLoger#4]
I run this app in pycharm and block by error:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbd in position 59: invalid start byte
then i try to add:
reload(sys)
sys.setdefaultencoding('utf8')
on the head of manage.py ,but it dosen't work ?
help?

---Detail error----
Traceback (most recent call last):
  File "C:/Users/xaiolos/Desktop/pythonѧϰ/NSLoger-master/manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Python27\lib\site-packages\django\core\management\__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "D:\Python27\lib\site-packages\django\core\management\__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Python27\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 62, in execute
    super(Command, self).execute(*args, **options)
  File "D:\Python27\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "D:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 101, in handle
    self.run(**options)
  File "D:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 110, in run
    autoreload.main(self.inner_run, None, options)
  File "D:\Python27\lib\site-packages\django\utils\autoreload.py", line 341, in main
    reloader(wrapped_main_func, args, kwargs)
  File "D:\Python27\lib\site-packages\django\utils\autoreload.py", line 312, in python_reloader
    exit_code = restart_with_reloader()
  File "D:\Python27\lib\site-packages\django\utils\autoreload.py", line 294, in restart_with_reloader
    str_value = force_bytes(new_environ[key], encoding=encoding)
  File "D:\Python27\lib\site-packages\django\utils\encoding.py", line 124, in force_bytes
    return s.decode('utf-8', errors).encode(encoding, errors)
  File "D:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbd in position 59: invalid start byte

Process finished with exit code 1

**Comment by isaced** [comment]
Please use Python3

**Comment by miketwais** [comment]
Thank you!
